### ISSUE TITLE
Error Message Received - Missing declaration file.

### ISSUE THREAD

**Issue by glassputan** [grizzthedj/react-session#9]
I'm trying to use this for a website and am running into the issue "Could not find a declaration file for module 'react-client-session'.  '../node-modules/react-client-session/dist/App.js' implicitly has an 'any' type.  Try `npm i --save-dev @types/react-client-session` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-client-session';` ts(7016).

I tried the command and it fails, assuming nobody's defined the type.

**Comment by tommtt** [comment]
Experiencing the same problem.  I added the .d.ts file containing "declare module 'react-client-session'" and it doesn't display the error anymore, but it still doesn't work. 

Every time I try to use it I get this error:

TypeError: Cannot read properties of undefined (reading 'set')

Did you find a solution?

**Comment by fernandonavajas** [comment]
+1, the import dosent work

**Comment by grizzthedj** [comment]
Sorry for the late response - This is fixed in version `0.0.8` @fernandonavajas @tommtt @glassputan
